
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftANDORIMPLIESrightUNOTAND IMPLIES LPAREN NOT OR RPAREN VALexpression : VALexpression : NOT expression %prec UNOTexpression : expression OR expressionexpression : expression AND expressionexpression : expression IMPLIES expressionexpression : LPAREN expression RPAREN'
    
_lr_action_items = {'VAL':([0,3,4,5,6,7,],[2,2,2,2,2,2,]),'NOT':([0,3,4,5,6,7,],[3,3,3,3,3,3,]),'LPAREN':([0,3,4,5,6,7,],[4,4,4,4,4,4,]),'$end':([1,2,8,10,11,12,13,],[0,-1,-2,-3,-4,-5,-6,]),'OR':([1,2,8,9,10,11,12,13,],[5,-1,-2,5,-3,-4,-5,-6,]),'AND':([1,2,8,9,10,11,12,13,],[6,-1,-2,6,-3,-4,-5,-6,]),'IMPLIES':([1,2,8,9,10,11,12,13,],[7,-1,-2,7,-3,-4,-5,-6,]),'RPAREN':([2,8,9,10,11,12,13,],[-1,-2,13,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,5,6,7,],[1,8,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> VAL','expression',1,'p_expression_val','generateTruthTable.py',46),
  ('expression -> NOT expression','expression',2,'p_expression_not','generateTruthTable.py',52),
  ('expression -> expression OR expression','expression',3,'p_expression_or','generateTruthTable.py',57),
  ('expression -> expression AND expression','expression',3,'p_expression_and','generateTruthTable.py',63),
  ('expression -> expression IMPLIES expression','expression',3,'p_expression_IMPLIES','generateTruthTable.py',69),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_factor_expr','generateTruthTable.py',76),
]
